/**
 * Social preview images (og:image / twitter:image).
 *
 * Until now the site emitted no og:image at all, so every link shared on
 * WhatsApp — the channel this business actually books through — previewed as a
 * blank grey box. Files are generated by scripts/generate-og-images.mjs at the
 * 1200x630 both Facebook/WhatsApp and X expect, and committed to public/og/.
 *
 * One image per route: the picture does not change with language, so EN and PT
 * share a file. Only the alt text is translated.
 */
import type { RouteKey } from './routes';
import type { Locale } from './routes';

interface OgEntry {
  image: string;
  alt: Record<Locale, string>;
}

export const OG: Record<RouteKey, OgEntry> = {
  home: {
    image: '/og/home.jpg',
    alt: {
      en: 'The crater lakes of Sete Cidades on São Miguel, Azores',
      pt: 'As lagoas das Sete Cidades, na ilha de São Miguel, Açores',
    },
  },
  properties: {
    image: '/og/properties.jpg',
    alt: {
      en: 'Kitchen and dining area of the Ramalho three-bedroom apartment in Ponta Delgada',
      pt: 'Cozinha e zona de refeições do apartamento Ramalho T3, em Ponta Delgada',
    },
  },
  ramalho: {
    image: '/og/ramalho.jpg',
    alt: {
      en: 'Living room with corner sofa and TV in the Ramalho three-bedroom apartment, Ponta Delgada',
      pt: 'Sala de estar com sofá de canto e televisão no apartamento Ramalho T3, Ponta Delgada',
    },
  },
  amorim: {
    image: '/og/amorim.jpg',
    alt: {
      en: 'Architectural render of the open-plan living room and kitchen of the Amorim two-bedroom apartment',
      pt: 'Imagem 3D da sala e cozinha em plano aberto do apartamento Amorim T2',
    },
  },
  duplex: {
    image: '/og/amorim-duplex.jpg',
    alt: {
      en: 'Architectural render of the dining area and breakfast bar of the Amorim two-bedroom duplex',
      pt: 'Imagem 3D da zona de refeições e bancada de pequeno-almoço do duplex Amorim T2',
    },
  },
  about: {
    image: '/og/about.jpg',
    alt: {
      en: 'The bell tower of the Igreja Matriz de São Sebastião in central Ponta Delgada',
      pt: 'A torre sineira da Igreja Matriz de São Sebastião, no centro de Ponta Delgada',
    },
  },
  faq: {
    image: '/og/faq.jpg',
    alt: {
      en: 'Kitchen with a dining table for six in the Ramalho apartment, Ponta Delgada',
      pt: 'Cozinha com mesa para seis pessoas no apartamento Ramalho, Ponta Delgada',
    },
  },
  guide: {
    image: '/og/guide.jpg',
    alt: {
      en: 'Scenes from São Miguel: an Azorean pineapple, a crater lake and the Portas da Cidade in Ponta Delgada',
      pt: 'Imagens de São Miguel: um ananás dos Açores, uma lagoa e as Portas da Cidade em Ponta Delgada',
    },
  },
};
